### ISSUE TITLE
clownery

### ISSUE THREAD

**Issue by AcaiBerii** [notperry1234567890/FutureX-SRC#1]
many

**Comment by notperry1234567890** [comment]
are u kidding they haven't changed anything they only renamed stuff in main class and added a skidded rpc and couldn't even refactor client

**Comment by AcaiBerii** [comment]
> are u kidding they haven't changed anything they only renamed stuff in main class and added a skidded rpc and couldn't even refactor the client

lol im making fun of how retarded futurex is chill

**Comment by notperry1234567890** [comment]
> > are u kidding they haven't changed anything they only renamed stuff in main class and added a skidded rpc and couldn't even refactor the client
> 
> lol im making fun of how retarded futurex is chill

yeah i am aswell?
